import type { AdviceReport } from "./types"

export const mockAdviceReport: AdviceReport = {
  meta: {
    generated_at: "2026-04-26T10:00:00.000Z",
    ucar_name: "University of Carthage",
    competitors_analyzed: 10,
    data_confidence: "medium",
  },
  ranking_snapshot: {
    ucar: {
      name: "University of Carthage",
      world_rank: null,
      note: "En cours d'enregistrement auprès des classements",
    },
    competitors: [
      {
        world_rank: 41,
        name: "Université de Tunis El Manar",
        country: "Tunisia",
        presence: 186,
        impact: 42,
        openness: 9,
        excellence: 201,
      },
      {
        world_rank: 66,
        name: "University of Sfax",
        country: "Tunisia",
        presence: 201,
        impact: 61,
        openness: 43,
        excellence: 183,
      },
      {
        world_rank: 101,
        name: "University of Monastir",
        country: "Tunisia",
        presence: 201,
        impact: 135,
        openness: 45,
        excellence: 137,
      },
      {
        world_rank: 108,
        name: "Université de Sousse",
        country: "Tunisia",
        presence: 201,
        impact: 112,
        openness: 78,
        excellence: 195,
      },
      {
        world_rank: 118,
        name: "Université Mohammed V de Rabat",
        country: "Morocco",
        presence: 51,
        impact: 133,
        openness: 19,
        excellence: 201,
      },
      {
        world_rank: 24,
        name: "Lebanese American University",
        country: "Lebanon",
        presence: 40,
        impact: 37,
        openness: 17,
        excellence: 30,
      },
      {
        world_rank: 36,
        name: "Alexandria University",
        country: "Egypt",
        presence: 5,
        impact: 15,
        openness: 15,
        excellence: 98,
      },
      {
        world_rank: 109,
        name: "Badji Mokhtar-Annaba University",
        country: "Algeria",
        presence: 137,
        impact: 151,
        openness: 99,
        excellence: 201,
      },
      {
        world_rank: 13,
        name: "The American University in Cairo",
        country: "Egypt",
        presence: 4,
        impact: 9,
        openness: 61,
        excellence: 44,
      },
      {
        world_rank: 191,
        name: "Université de Gabès",
        country: "Tunisia",
        presence: 201,
        impact: 151,
        openness: 114,
        excellence: 180,
      },
    ],
  },
  analysis: {
    competitor_summary: [
      {
        name: "Université de Tunis El Manar",
        world_rank: 41,
        beats_ucar_in: ["PRESENCE", "IMPACT", "EXCELLENCE"],
      },
      {
        name: "University of Sfax",
        world_rank: 66,
        beats_ucar_in: ["PRESENCE", "IMPACT"],
      },
      {
        name: "Lebanese American University",
        world_rank: 24,
        beats_ucar_in: ["IMPACT", "EXCELLENCE"],
      },
    ],
    critical_gaps: [
      {
        rank: 1,
        dimension: "PRESENCE",
        gap_description:
          "Renforcer la visibilité numérique et l'indexation web pour améliorer le classement Webometrics.",
        ucar_metric: "unknown",
        best_competitor_metric: 4,
        best_competitor_name: "The American University in Cairo",
        estimated_rank_improvement: "+15-25 places si amélioré de 50%",
        actions: [
          {
            action: "Optimiser le référencement (SEO) du site web institutionnel",
            effort: "moyen",
            timeline: "1-3 mois",
            impact: "moyen",
          },
          {
            action: "Augmenter la présence sur les plateformes académiques (ResearchGate, Academia.edu)",
            effort: "faible",
            timeline: "immédiat",
            impact: "moyen",
          },
        ],
      },
      {
        rank: 2,
        dimension: "IMPACT",
        gap_description: "Augmenter le nombre de citations et l'impact académique des publications.",
        ucar_metric: "unknown",
        best_competitor_metric: 9,
        best_competitor_name: "The American University in Cairo",
        estimated_rank_improvement: "+10-20 places si amélioré de 60%",
        actions: [
          {
            action: "Promouvoir les publications dans des revues à haut impact",
            effort: "moyen",
            timeline: "3-6 mois",
            impact: "élevé",
          },
          {
            action: "Encourager les collaborations de recherche internationales",
            effort: "élevé",
            timeline: "6-12 mois",
            impact: "élevé",
          },
        ],
      },
      {
        rank: 3,
        dimension: "OPENNESS",
        gap_description: "Améliorer l'accessibilité et la transparence des données institutionnelles.",
        ucar_metric: "unknown",
        best_competitor_metric: 9,
        best_competitor_name: "Université de Tunis El Manar",
        estimated_rank_improvement: "+8-15 places si amélioré de 40%",
        actions: [
          {
            action: "Mettre en place un référentiel institutionnel pour les publications",
            effort: "moyen",
            timeline: "2-4 mois",
            impact: "moyen",
          },
        ],
      },
    ],
    quick_wins: [
      {
        action: "Créer des profils Google Scholar pour tous les chercheurs",
        timeline: "1-2 semaines",
        pillar_affected: "PRESENCE",
      },
      {
        action: "Publier des communiqués de presse sur les avancées académiques majeures",
        timeline: "immédiat",
        pillar_affected: "PRESENCE",
      },
    ],
    strategic_priorities: [
      "Stabiliser les métriques Webometrics en assurant que le nom de l'université est correctement enregistré auprès des indexeurs.",
      "Institutionnaliser un benchmark mensuel des concurrents avec suivi des KPI par pilier.",
      "Augmenter la visibilité des publications en accès ouvert via un dépôt institutionnel.",
      "Améliorer la discoverabilité internationale à travers un contenu multilingue (FR/EN) et une présence partenaire renforcée.",
    ],
    data_confidence: "medium",
    notes: "Données de démonstration. Connecter à Advice Server pour les données en direct.",
  },
  executive_summary:
    "L'Université de Carthage est en cours de positionnement international selon les critères Webometrics. Les principaux leviers d'amélioration se situent sur : (1) la présence numérique et l'indexation (quick wins immédiats possibles), (2) l'impact académique des publications (6-12 mois), et (3) l'ouverture et la transparence des données (6-12 mois).\n\nLa stratégie recommandée combine des actions rapides (profils chercheurs, communiqués) et des chantiers structurants (référentiel institutionnel, collaborations internationales) pour une amélioration progressive et durable du classement.",
}
