import type { User } from './types'

export const MOCK_USERS: User[] = [
  // ===== PRÉSIDENCE (level 0) =====
  { id: 'u-001', email: 'president@ucar.tn', password: 'ucar2024', firstName: 'Nadia', lastName: 'Mzoughi Aguir', role: 'president', roleLabel: 'Présidente de l\'Université de Carthage', serviceId: 'presidence', serviceName: 'Présidence', level: 0, assignedBy: 'system', canAccessInstitutions: ['all'], isActive: true, title: 'Pr.', phone: '+216 71 749 100' },
  { id: 'u-002', email: 'mongi.besbes@ucar.tn', password: 'ucar2024', firstName: 'Mongi', lastName: 'Besbes', role: 'president', roleLabel: 'Vice-Président de l\'Université de Carthage', serviceId: 'presidence', serviceName: 'Présidence', level: 0, assignedBy: 'system', canAccessInstitutions: ['all'], isActive: true, title: 'Pr.' },
  { id: 'u-003', email: 'afef.abdelkrim@ucar.tn', password: 'ucar2024', firstName: 'Afef', lastName: 'Abdelkrim', role: 'president', roleLabel: 'Vice-Présidente de l\'Université de Carthage', serviceId: 'presidence', serviceName: 'Présidence', level: 0, assignedBy: 'system', canAccessInstitutions: ['all'], isActive: true, title: 'Pr.' },
  { id: 'u-004', email: 'wahida.boutabba@ucar.tn', password: 'ucar2024', firstName: 'Wahida', lastName: 'Boutabba', role: 'svc_secretaire', roleLabel: 'Secrétaire Générale', serviceId: 'secretariat', serviceName: 'Secrétariat Général', level: 1, assignedBy: 'u-001', canAccessInstitutions: ['all'], isActive: true },
  // ===== SERVICE RH (level 2) =====
  { id: 'u-010', email: 'mohamed.khedimallah@ucar.tn', password: 'ucar2024', firstName: 'Mohamed', lastName: 'Khedimallah', role: 'svc_rh', roleLabel: 'Directeur du Service RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-011', email: 'belgacem.chatti@ucar.tn', password: 'ucar2024', firstName: 'Belgacem', lastName: 'Chatti', role: 'svc_rh', roleLabel: 'Chef du Service RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-012', email: 'oussema.khimissi@ucar.tn', password: 'ucar2024', firstName: 'Oussema', lastName: 'Khimissi', role: 'svc_rh', roleLabel: 'Administrateur RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-010', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-013', email: 'chiraz.hajji@ucar.tn', password: 'ucar2024', firstName: 'Chiraz', lastName: 'Hajji', role: 'svc_rh', roleLabel: 'Administrateur RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-010', canAccessInstitutions: ['enit'], isActive: true },
  { id: 'u-014', email: 'ahlem.hkimi@ucar.tn', password: 'ucar2024', firstName: 'Ahlem', lastName: 'Hkimi', role: 'svc_rh', roleLabel: 'Administrateur RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-010', canAccessInstitutions: ['fst'], isActive: true },
  { id: 'u-015', email: 'essia.saidi@ucar.tn', password: 'ucar2024', firstName: 'Essia', lastName: 'Saidi', role: 'svc_rh', roleLabel: 'Administrateur RH', serviceId: 'svc_rh', serviceName: 'Service Ressources Humaines', level: 2, assignedBy: 'u-010', canAccessInstitutions: ['fsegt'], isActive: true },
  // ===== SERVICE ENSEIGNEMENT (level 2) =====
  { id: 'u-020', email: 'samar.benyounes@ucar.tn', password: 'ucar2024', firstName: 'Samar', lastName: 'Ben Younes', role: 'svc_enseignement', roleLabel: 'Directrice du Personnel Enseignant', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-021', email: 'asma.hfaiedh@ucar.tn', password: 'ucar2024', firstName: 'Asma', lastName: 'Hfaiedh', role: 'svc_enseignement', roleLabel: 'Chef du Personnel Enseignant', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-020', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-022', email: 'chiraz.mejri@ucar.tn', password: 'ucar2024', firstName: 'Chiraz', lastName: 'Mejri', role: 'svc_enseignement', roleLabel: 'Administrateur Enseignement', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-020', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-023', email: 'ahlem.glaoui@ucar.tn', password: 'ucar2024', firstName: 'Ahlem', lastName: 'Glaoui', role: 'svc_enseignement', roleLabel: 'Administrateur Enseignement', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-020', canAccessInstitutions: ['enit'], isActive: true },
  { id: 'u-024', email: 'nedra.benchabene@ucar.tn', password: 'ucar2024', firstName: 'Nedra', lastName: 'Ben Chabene', role: 'svc_enseignement', roleLabel: 'Administrateur Enseignement', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-020', canAccessInstitutions: ['fst'], isActive: true },
  { id: 'u-025', email: 'faten.rihani@ucar.tn', password: 'ucar2024', firstName: 'Faten', lastName: 'Rihani', role: 'svc_enseignement', roleLabel: 'Administrateur Enseignement', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 2, assignedBy: 'u-020', canAccessInstitutions: ['fsegt'], isActive: true },
  // ===== SERVICE BIBLIOTHÈQUE (level 2) =====
  { id: 'u-030', email: 'ridha.makadmi@ucar.tn', password: 'ucar2024', firstName: 'Ridha', lastName: 'Makadmi', role: 'svc_bibliotheque', roleLabel: 'Directeur de la Bibliothèque', serviceId: 'svc_bibliotheque', serviceName: 'Service Bibliothèque', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-031', email: 'fatma.hmila@ucar.tn', password: 'ucar2024', firstName: 'Fatma Zahra', lastName: 'Hmila', role: 'svc_bibliotheque', roleLabel: 'Chef de la Bibliothèque', serviceId: 'svc_bibliotheque', serviceName: 'Service Bibliothèque', level: 2, assignedBy: 'u-030', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-032', email: 'imen.habbachi@ucar.tn', password: 'ucar2024', firstName: 'Imen', lastName: 'Habbachi', role: 'svc_bibliotheque', roleLabel: 'Administrateur Bibliothèque', serviceId: 'svc_bibliotheque', serviceName: 'Service Bibliothèque', level: 2, assignedBy: 'u-030', canAccessInstitutions: ['enit'], isActive: true },
  // ===== SERVICE FINANCES (level 2) =====
  { id: 'u-040', email: 'samir.ghodhbani@ucar.tn', password: 'ucar2024', firstName: 'Samir', lastName: 'Ghodhbani', role: 'svc_finances', roleLabel: 'Directeur des Affaires Financières', serviceId: 'svc_finances', serviceName: 'Service Affaires Financières', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-041', email: 'ines.khodjet@ucar.tn', password: 'ucar2024', firstName: 'Ines', lastName: 'Khodjet el Khil', role: 'svc_finances', roleLabel: 'Administrateur Finances', serviceId: 'svc_finances', serviceName: 'Service Affaires Financières', level: 2, assignedBy: 'u-040', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-042', email: 'walid.bessaad@ucar.tn', password: 'ucar2024', firstName: 'Walid', lastName: 'Bessaad', role: 'svc_finances', roleLabel: 'Administrateur Finances', serviceId: 'svc_finances', serviceName: 'Service Affaires Financières', level: 2, assignedBy: 'u-040', canAccessInstitutions: ['enit'], isActive: true },
  { id: 'u-043', email: 'seif.laghar@ucar.tn', password: 'ucar2024', firstName: 'Seif', lastName: 'Laghar', role: 'svc_finances', roleLabel: 'Administrateur Finances', serviceId: 'svc_finances', serviceName: 'Service Affaires Financières', level: 2, assignedBy: 'u-040', canAccessInstitutions: ['fst'], isActive: true },
  // ===== SERVICE ÉQUIPEMENT (level 2) =====
  { id: 'u-050', email: 'neffisa.razouk@ucar.tn', password: 'ucar2024', firstName: 'Neffisa', lastName: 'Razouk', role: 'svc_equipement', roleLabel: 'Chef du Service Équipement', serviceId: 'svc_equipement', serviceName: 'Service Équipement & Bâtiments', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-051', email: 'safa.trabelsi@ucar.tn', password: 'ucar2024', firstName: 'Safa', lastName: 'Trabelsi', role: 'svc_equipement', roleLabel: 'Chef du Service Bâtiment', serviceId: 'svc_equipement', serviceName: 'Service Équipement & Bâtiments', level: 2, assignedBy: 'u-050', canAccessInstitutions: ['ensi', 'enit'], isActive: true },
  { id: 'u-052', email: 'hamdi.moulhi@ucar.tn', password: 'ucar2024', firstName: 'Hamdi', lastName: 'Moulhi', role: 'svc_equipement', roleLabel: 'Administrateur Équipement', serviceId: 'svc_equipement', serviceName: 'Service Équipement & Bâtiments', level: 2, assignedBy: 'u-050', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-053', email: 'maher.riahi@ucar.tn', password: 'ucar2024', firstName: 'Maher', lastName: 'Riahi', role: 'svc_equipement', roleLabel: 'Administrateur Équipement', serviceId: 'svc_equipement', serviceName: 'Service Équipement & Bâtiments', level: 2, assignedBy: 'u-050', canAccessInstitutions: ['enit'], isActive: true },
  { id: 'u-054', email: 'akram.azzabi@ucar.tn', password: 'ucar2024', firstName: 'Akram', lastName: 'Azzabi', role: 'svc_equipement', roleLabel: 'Administrateur Équipement', serviceId: 'svc_equipement', serviceName: 'Service Équipement & Bâtiments', level: 2, assignedBy: 'u-050', canAccessInstitutions: ['fst'], isActive: true },
  // ===== SERVICE INFORMATIQUE (level 2) =====
  { id: 'u-060', email: 'iness.hmissi@ucar.tn', password: 'ucar2024', firstName: 'Iness', lastName: 'Hmissi', role: 'svc_informatique', roleLabel: 'Chef du Service Informatique', serviceId: 'svc_informatique', serviceName: 'Service Informatique', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-061', email: 'sonia.mgadmini@ucar.tn', password: 'ucar2024', firstName: 'Sonia', lastName: 'Mgadmini', role: 'svc_informatique', roleLabel: 'Technicienne IT Principale', serviceId: 'svc_informatique', serviceName: 'Service Informatique', level: 2, assignedBy: 'u-060', canAccessInstitutions: ['ensi', 'enit'], isActive: true },
  { id: 'u-062', email: 'kais.laamar@ucar.tn', password: 'ucar2024', firstName: 'Kais', lastName: 'Laamar', role: 'svc_informatique', roleLabel: 'Technicien IT Principal', serviceId: 'svc_informatique', serviceName: 'Service Informatique', level: 2, assignedBy: 'u-060', canAccessInstitutions: ['fst', 'fsegt'], isActive: true },
  // ===== SERVICE BUDGET (level 2) =====
  { id: 'u-070', email: 'abdelkader.dehliz@ucar.tn', password: 'ucar2024', firstName: 'Abdelkader', lastName: 'Dehliz', role: 'svc_budget', roleLabel: 'Directeur du Budget', serviceId: 'svc_budget', serviceName: 'Service Budget', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-071', email: 'amira.nouira@ucar.tn', password: 'ucar2024', firstName: 'Amira', lastName: 'Nouira', role: 'svc_budget', roleLabel: 'Chef du Service Budget', serviceId: 'svc_budget', serviceName: 'Service Budget', level: 2, assignedBy: 'u-070', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-072', email: 'mouna.bensaid@ucar.tn', password: 'ucar2024', firstName: 'Mouna', lastName: 'Ben Said', role: 'svc_budget', roleLabel: 'Administrateur Budget', serviceId: 'svc_budget', serviceName: 'Service Budget', level: 2, assignedBy: 'u-070', canAccessInstitutions: ['ensi'], isActive: true },
  // ===== SERVICE JURIDIQUE (level 2) =====
  { id: 'u-080', email: 'rawia.elwafi@ucar.tn', password: 'ucar2024', firstName: 'Rawia', lastName: 'Elwafi', role: 'svc_juridique', roleLabel: 'Chef du Service Juridique', serviceId: 'svc_juridique', serviceName: 'Service Affaires Juridiques', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-081', email: 'rihab.elaamri@ucar.tn', password: 'ucar2024', firstName: 'Rihab', lastName: 'Elaamri', role: 'svc_juridique', roleLabel: 'Administrateur Juridique', serviceId: 'svc_juridique', serviceName: 'Service Affaires Juridiques', level: 2, assignedBy: 'u-080', canAccessInstitutions: ['ensi'], isActive: true },
  // ===== SERVICE ACADÉMIQUE (level 2) =====
  { id: 'u-090', email: 'hatem.khaloui@ucar.tn', password: 'ucar2024', firstName: 'Hatem', lastName: 'Khaloui', role: 'svc_academique', roleLabel: 'Directeur des Affaires Académiques', serviceId: 'svc_academique', serviceName: 'Service Affaires Académiques', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-091', email: 'imen.chaouachi@ucar.tn', password: 'ucar2024', firstName: 'Imen', lastName: 'Chaouachi', role: 'svc_academique', roleLabel: 'Chef des Affaires Académiques', serviceId: 'svc_academique', serviceName: 'Service Affaires Académiques', level: 2, assignedBy: 'u-090', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-092', email: 'mourad.jallouli@ucar.tn', password: 'ucar2024', firstName: 'Mourad', lastName: 'Jallouli', role: 'svc_academique', roleLabel: 'Administrateur Académique', serviceId: 'svc_academique', serviceName: 'Service Affaires Académiques', level: 2, assignedBy: 'u-090', canAccessInstitutions: ['ensi'], isActive: true },
  // ===== SERVICE RECHERCHE (level 2) =====
  { id: 'u-100', email: 'mehrez.hammami@ucar.tn', password: 'ucar2024', firstName: 'Mehrez', lastName: 'Hammami', role: 'svc_recherche', roleLabel: 'Chef du Service Recherche Scientifique', serviceId: 'svc_recherche', serviceName: 'Service Recherche & Coopération', level: 2, assignedBy: 'u-001', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt', 'isamm', 'isg', 'iscc', 'issat', 'isbm', 'iset', 'insat', 'supcom'], isActive: true },
  { id: 'u-101', email: 'hajer.ferchichi@ucar.tn', password: 'ucar2024', firstName: 'Hajer', lastName: 'Ferchichi', role: 'svc_recherche', roleLabel: 'Chef du Service Coopération', serviceId: 'svc_recherche', serviceName: 'Service Recherche & Coopération', level: 2, assignedBy: 'u-100', canAccessInstitutions: ['ensi', 'enit', 'fst', 'fsegt'], isActive: true },
  { id: 'u-102', email: 'leila.trabelsi@ucar.tn', password: 'ucar2024', firstName: 'Leila', lastName: 'Trabelsi', role: 'svc_recherche', roleLabel: 'Administrateur Recherche', serviceId: 'svc_recherche', serviceName: 'Service Recherche & Coopération', level: 2, assignedBy: 'u-100', canAccessInstitutions: ['ensi'], isActive: true },
  // ===== TEACHERS =====
  { id: 'u-200', email: 'ahmed.benali@ensi.tn', password: 'teacher2024', firstName: 'Ahmed', lastName: 'Ben Ali', role: 'teacher', roleLabel: 'Enseignant - ENSI', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 3, assignedBy: 'u-021', canAccessInstitutions: ['ensi'], isActive: true, title: 'Dr.' },
  { id: 'u-201', email: 'sana.mejri@fst.tn', password: 'teacher2024', firstName: 'Sana', lastName: 'Mejri', role: 'teacher', roleLabel: 'Enseignante - FST', serviceId: 'svc_enseignement', serviceName: 'Service Personnel Enseignant', level: 3, assignedBy: 'u-021', canAccessInstitutions: ['fst'], isActive: true, title: 'Dr.' },
  // ===== STUDENTS =====
  { id: 'u-300', email: 'oussema.harrabi@ensi.tn', password: 'student2024', firstName: 'Oussema', lastName: 'Harrabi', role: 'student', roleLabel: 'Étudiant - ENSI', serviceId: 'svc_academique', serviceName: 'Service Affaires Académiques', level: 4, assignedBy: 'u-091', canAccessInstitutions: ['ensi'], isActive: true },
  { id: 'u-301', email: 'eya.trabelsi@ensi.tn', password: 'student2024', firstName: 'Eya', lastName: 'Trabelsi', role: 'student', roleLabel: 'Étudiante - ENSI', serviceId: 'svc_academique', serviceName: 'Service Affaires Académiques', level: 4, assignedBy: 'u-091', canAccessInstitutions: ['ensi'], isActive: true },
]

export function findUserByEmail(email: string): User | undefined {
  return MOCK_USERS.find(u => u.email === email && u.isActive)
}

export function authenticateUser(email: string, password: string): User | undefined {
  const user = MOCK_USERS.find(u => u.email === email && u.password === password && u.isActive)
  return user
}
